name: infamainsurance

on:
  push:
    branches:
      - 'master'

  pull_request:
    branches:
      - 'master'
    
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: infamainsurance tests
        run: echo 'testing'